#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
usage: ci-product-bundle.sh [options]

Creates a CAE/CI-ready bundle config inside WORKDIR and runs the full
product-bundle flow in one command.

Required:
  --workdir PATH
  --product-version VERSION
  --k3s-version VERSION
  --control-plane-image-ref REF
  --ctl-repo-source PATH_OR_URL

Optional:
  --release-input-source PATH_OR_URL
  --release-input-version VERSION
  --release-input-fetch-template TEMPLATE
  --config-out PATH                 Defaults to WORKDIR/product-bundle.env.
  --inputs-dir PATH                 Defaults to WORKDIR/inputs.
  --ctl-repo-ref REF
  --chart-version VERSION           Defaults to PRODUCT_VERSION.
  --argo-version VERSION            Defaults to deferred.
  --os-version VERSION              Defaults to 24.04.
  --values-file PATH
  --control-plane-image PATH
  --argo-crds PATH
  --k3s-binary PATH
  --k3s-install-script PATH
  --k3s-airgap-images PATH
  --sample-mode 0|1                 Defaults to 0.
  --write-config-only               Write the config and stop.

The script writes a concrete env file first so CAE/CI logs always show the
exact resolved config used for the bundle run.
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

WORKDIR=""
CONFIG_OUT=""
INPUTS_DIR=""
PRODUCT_VERSION=""
K3S_VERSION=""
CONTROL_PLANE_IMAGE_REF=""
RELEASE_INPUT_SOURCE=""
RELEASE_INPUT_VERSION=""
RELEASE_INPUT_FETCH_TEMPLATE=""
CTL_REPO_SOURCE=""
CTL_REPO_REF=""
CHART_VERSION=""
ARGO_VERSION="deferred"
OS_VERSION="24.04"
VALUES_FILE=""
CONTROL_PLANE_IMAGE=""
ARGO_CRDS=""
K3S_BINARY=""
K3S_INSTALL_SCRIPT=""
K3S_AIRGAP_IMAGES=""
SAMPLE_MODE="0"
WRITE_CONFIG_ONLY="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workdir) WORKDIR="${2:-}"; shift 2 ;;
    --config-out) CONFIG_OUT="${2:-}"; shift 2 ;;
    --inputs-dir) INPUTS_DIR="${2:-}"; shift 2 ;;
    --product-version) PRODUCT_VERSION="${2:-}"; shift 2 ;;
    --k3s-version) K3S_VERSION="${2:-}"; shift 2 ;;
    --control-plane-image-ref) CONTROL_PLANE_IMAGE_REF="${2:-}"; shift 2 ;;
    --release-input-source) RELEASE_INPUT_SOURCE="${2:-}"; shift 2 ;;
    --release-input-version) RELEASE_INPUT_VERSION="${2:-}"; shift 2 ;;
    --release-input-fetch-template) RELEASE_INPUT_FETCH_TEMPLATE="${2:-}"; shift 2 ;;
    --ctl-repo-source) CTL_REPO_SOURCE="${2:-}"; shift 2 ;;
    --ctl-repo-ref) CTL_REPO_REF="${2:-}"; shift 2 ;;
    --chart-version) CHART_VERSION="${2:-}"; shift 2 ;;
    --argo-version) ARGO_VERSION="${2:-}"; shift 2 ;;
    --os-version) OS_VERSION="${2:-}"; shift 2 ;;
    --values-file) VALUES_FILE="${2:-}"; shift 2 ;;
    --control-plane-image) CONTROL_PLANE_IMAGE="${2:-}"; shift 2 ;;
    --argo-crds) ARGO_CRDS="${2:-}"; shift 2 ;;
    --k3s-binary) K3S_BINARY="${2:-}"; shift 2 ;;
    --k3s-install-script) K3S_INSTALL_SCRIPT="${2:-}"; shift 2 ;;
    --k3s-airgap-images) K3S_AIRGAP_IMAGES="${2:-}"; shift 2 ;;
    --sample-mode) SAMPLE_MODE="${2:-}"; shift 2 ;;
    --write-config-only) WRITE_CONFIG_ONLY="1"; shift 1 ;;
    --help|-h) usage; exit 0 ;;
    *)
      echo "ci-product-bundle: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

require_arg() {
  local name="$1"
  local value="$2"
  if [[ -z "${value}" ]]; then
    echo "ci-product-bundle: missing required argument ${name}" >&2
    usage >&2
    exit 2
  fi
}

require_arg --workdir "${WORKDIR}"
require_arg --product-version "${PRODUCT_VERSION}"
require_arg --k3s-version "${K3S_VERSION}"
require_arg --control-plane-image-ref "${CONTROL_PLANE_IMAGE_REF}"
require_arg --ctl-repo-source "${CTL_REPO_SOURCE}"

if [[ "${SAMPLE_MODE}" != "1" ]]; then
  if [[ -z "${RELEASE_INPUT_SOURCE}" && ( -z "${RELEASE_INPUT_VERSION}" || -z "${RELEASE_INPUT_FETCH_TEMPLATE}" ) ]]; then
    echo "ci-product-bundle: set --release-input-source or both --release-input-version and --release-input-fetch-template" >&2
    usage >&2
    exit 2
  fi
fi

WORKDIR="$(cd "$(dirname "${WORKDIR}")" && pwd)/$(basename "${WORKDIR}")"
INPUTS_DIR="${INPUTS_DIR:-${WORKDIR}/inputs}"
CONFIG_OUT="${CONFIG_OUT:-${WORKDIR}/product-bundle.env}"
CHART_VERSION="${CHART_VERSION:-${PRODUCT_VERSION}}"

mkdir -p "${WORKDIR}" "$(dirname "${CONFIG_OUT}")"

write_var() {
  local name="$1"
  local value="$2"
  printf '%s=' "${name}"
  printf '%q\n' "${value}"
}

{
  cat <<'EOF'
# Generated by scripts/package/ci-product-bundle.sh
# Safe to archive as CI evidence and reuse for reruns.
EOF
  echo
  write_var WORKDIR "${WORKDIR}"
  write_var PRODUCT_VERSION "${PRODUCT_VERSION}"
  write_var K3S_VERSION "${K3S_VERSION}"
  write_var CONTROL_PLANE_IMAGE_REF "${CONTROL_PLANE_IMAGE_REF}"
  write_var RELEASE_INPUT_SOURCE "${RELEASE_INPUT_SOURCE}"
  write_var RELEASE_INPUT_VERSION "${RELEASE_INPUT_VERSION}"
  write_var RELEASE_INPUT_FETCH_TEMPLATE "${RELEASE_INPUT_FETCH_TEMPLATE}"
  write_var CTL_REPO_SOURCE "${CTL_REPO_SOURCE}"
  write_var SAMPLE_MODE "${SAMPLE_MODE}"
  write_var INPUTS_DIR "${INPUTS_DIR}"
  write_var CTL_REPO_REF "${CTL_REPO_REF}"
  write_var CHART_VERSION "${CHART_VERSION}"
  write_var ARGO_VERSION "${ARGO_VERSION}"
  write_var OS_VERSION "${OS_VERSION}"
  write_var VALUES_FILE "${VALUES_FILE}"
  write_var CONTROL_PLANE_IMAGE "${CONTROL_PLANE_IMAGE}"
  write_var ARGO_CRDS "${ARGO_CRDS}"
  write_var K3S_BINARY "${K3S_BINARY}"
  write_var K3S_INSTALL_SCRIPT "${K3S_INSTALL_SCRIPT}"
  write_var K3S_AIRGAP_IMAGES "${K3S_AIRGAP_IMAGES}"
} >"${CONFIG_OUT}"

echo "generated bundle config:"
echo "  ${CONFIG_OUT}"

if [[ "${WRITE_CONFIG_ONLY}" == "1" ]]; then
  exit 0
fi

make -C "${REPO_ROOT}" product-bundle CONFIG="${CONFIG_OUT}"
