// Package k3s owns K3s installation, configuration, ownership, and status
// for the appliance: rendering the release-owned config file and systemd
// unit, deciding whether an existing K3s on the host may be reused, and
// interpreting its health. See "K3s Ownership" in docs/release-plan.md.
package k3s

import (
	"fmt"
	"strings"
)

// Config is the appliance-owned K3s configuration. It is always written
// as a file (never passed via environment variables), per "K3s
// configuration is written as files rather than relying on transient
// installer environment variables."
type Config struct {
	NodeName string
	DataDir  string
	TLSSANs  []string
}

// Render produces the config.yaml content for /etc/rancher/k3s/config.yaml.
// This is the initial v1 baseline field set; product-specific tuning
// arrives once appliance-code's configuration schema pins additional
// values (see Repository Boundary in the plan).
func (c Config) Render() string {
	var b strings.Builder
	b.WriteString("# Generated by appliance install; do not edit by hand.\n")
	fmt.Fprintf(&b, "node-name: %q\n", c.NodeName)
	fmt.Fprintf(&b, "data-dir: %q\n", c.DataDir)
	b.WriteString("write-kubeconfig-mode: \"0640\"\n")

	if len(c.TLSSANs) > 0 {
		b.WriteString("tls-san:\n")
		for _, san := range c.TLSSANs {
			fmt.Fprintf(&b, "  - %q\n", san)
		}
	}

	return b.String()
}
